[pytest]

# Módulo de configuración de Django (AJUSTAR a tu proyecto real).
DJANGO_SETTINGS_MODULE = config.settings

# Patrón de archivos de tests.
python_files = tests.py test_*.py *_tests.py

# Opciones por defecto (verbose).
addopts = -v
